### ISSUE TITLE
Add of d3-scale-chromatic colours to the colour selection

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/word-cloud-generator#1]
Currently, the colour selection is very limited. 

If possible more colours from [here](https://github.com/d3/d3-scale-chromatic) can be added as options. Especially the diverging and sequential colours. 

Please do remember to test if the colours are working before submitting a PR and do your work on a feature branch if possible.

**Comment by agataxmascarenhas** [comment]
Hi! Can I be assigned to this? thank you!

**Comment by JianLoong** [comment]
Sure. 👍

**Comment by JianLoong** [comment]
Closed as handled by #17
