### ISSUE TITLE
Consistent names and ids for HTML elements. 

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/word-cloud-generator#3]
Currently, the behaviour of elements like radio boxes does not work as expected due to having inconsistent naming and ids. This fix should be a rather easy fix. 

Further explanation
- If you take a look [here](https://getbootstrap.com/docs/5.0/forms/checks-radios/#radios), notice how when the text element on radio boxes are clicked by the user, the automatically selects the radio box to be checked, this should be the case for this website too.
- This naming issue should not break any existing functionality.

**Comment by JanitaRiyaz** [comment]
i wanna do this.. plz assign this to me.

**Comment by JianLoong** [comment]
Sure. I have assigned this to you.

**Comment by JianLoong** [comment]
Closing issue as it is resolved in latest push.
