### ISSUE TITLE
There should be a feature where  the user can select the text generated.

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/word-cloud-generator#4]
Currently, all the words generated by the word cloud are only in upper cases, there should be a feature where the user can decide what types of words can be generated 
- all uppercase
- all lowercases
- the first character is uppercase

This would require more select boxes to be added on the front end too.

**Comment by rudychung** [comment]
Hi, I'd like to work on this. Could you assign it to me?

**Comment by JianLoong** [comment]
Sure. 🥂
